// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import java.util.HashMap;
import java.util.Map;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class CalculatorTest {
  public static WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/Users/Leonardo/IdeaProjects/SeleniumIdeTest/src/test/resources/geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void cleanUp(){
    // close driver
    driver.close();
  }

  @Test
  public void calculatorTest() {
    // open online calculator
    driver.get("https://www.calcolatriceonline.it/");
    driver.manage().window().setSize(new Dimension(788, 728));
    // do operation: 2x2
    driver.findElement(By.cssSelector(".button:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".button:nth-child(11)")).click();
    driver.findElement(By.cssSelector(".button:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".button:nth-child(20)")).click();
    driver.findElement(By.name("display")).click();
    {
      // verify if result is 4
      String value = driver.findElement(By.name("display")).getAttribute("value");
      assertThat(value, is("4"));
    }
    driver.findElement(By.cssSelector(".row:nth-child(2)")).click();
  }
}
